name: Build Crunchy-Downloader

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore CRD.sln

      - name: Build the solution
        run: dotnet build CRD.sln --configuration Release --no-restore

      - name: Run tests (optionnel)
        run: dotnet test CRD.sln --configuration Release --no-build

      - name: Publish CRD project
        run: dotnet publish CRD/CRD.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CRD-win-x64
          path: ./publish
